baseURL = 'http://blog.egreer.info/'
languageCode = 'en-us'
title = "Ewan's Blog"
theme = "congo"

[params.author]
name = "Ewan Greer"
image = "img/author.jpg"
headline = "checkout my cool website --> http://localhost:3000/"
bio = "golang developer based in the UK"
links = [{ github = "https://www.github.com/EwanGreer" }]

[services]
[services.disqus]
shortname = 'blog-egreer-info'
