baseURL = 'http://blog.egreer.info/'
languageCode = 'en-us'
title = "Ewan's Blog"
theme = "congo"

[params.author]
name = "Ewan Greer"
image = "img/author.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [{ github = "https://www.github.com/EwanGreer" }]

[services]
[services.disqus]
shortname = 'blog-egreer-info'
